-- Migration 016 down: Revert constraint renames back to engine_schema_entities

-- Revert constraints on engine_ontology_entities table
ALTER INDEX engine_ontology_entities_pkey RENAME TO engine_schema_entities_pkey;
ALTER INDEX engine_ontology_entities_ontology_id_name_key RENAME TO engine_schema_entities_ontology_id_name_key;
ALTER INDEX idx_engine_ontology_entities_ontology RENAME TO idx_engine_schema_entities_ontology;
ALTER INDEX idx_engine_ontology_entities_primary_location RENAME TO idx_engine_schema_entities_primary_location;
ALTER INDEX idx_engine_ontology_entities_project RENAME TO idx_engine_schema_entities_project;

ALTER TABLE engine_ontology_entities
    RENAME CONSTRAINT engine_ontology_entities_ontology_id_fkey TO engine_schema_entities_ontology_id_fkey;
ALTER TABLE engine_ontology_entities
    RENAME CONSTRAINT engine_ontology_entities_project_id_fkey TO engine_schema_entities_project_id_fkey;

-- Revert constraints on engine_ontology_entity_occurrences table
ALTER INDEX engine_ontology_entity_occurrences_pkey RENAME TO engine_schema_entity_occurrences_pkey;
ALTER INDEX engine_ontology_entity_occurrences_unique_location RENAME TO engine_schema_entity_occurren_entity_id_schema_name_table_n_key;
ALTER INDEX idx_engine_ontology_entity_occurrences_entity RENAME TO idx_engine_schema_entity_occurrences_entity;
ALTER INDEX idx_engine_ontology_entity_occurrences_role RENAME TO idx_engine_schema_entity_occurrences_role;
ALTER INDEX idx_engine_ontology_entity_occurrences_table RENAME TO idx_engine_schema_entity_occurrences_table;

ALTER TABLE engine_ontology_entity_occurrences
    RENAME CONSTRAINT engine_ontology_entity_occurrences_confidence_check TO engine_schema_entity_occurrences_confidence_check;
ALTER TABLE engine_ontology_entity_occurrences
    RENAME CONSTRAINT engine_ontology_entity_occurrences_entity_id_fkey TO engine_schema_entity_occurrences_entity_id_fkey;
