package models

import (
	"time"

	"github.com/google/uuid"
)

// Alert severity levels.
const (
	AlertSeverityCritical = "critical"
	AlertSeverityWarning  = "warning"
	AlertSeverityInfo     = "info"
)

// Alert status values.
const (
	AlertStatusOpen     = "open"
	AlertStatusResolved = "resolved"
	AlertStatusDismissed = "dismissed"
)

// Alert types generated by the alert trigger system.
const (
	AlertTypeSQLInjection       = "sql_injection_detected"
	AlertTypeUnusualQueryVolume = "unusual_query_volume"
	AlertTypeSensitiveTable     = "sensitive_table_access"
	AlertTypeLargeDataExport    = "large_data_export"
	AlertTypeAfterHoursAccess   = "after_hours_access"
	AlertTypeNewUserHighVolume  = "new_user_high_volume"
	AlertTypeRepeatedErrors     = "repeated_errors"
)

// AuditAlert represents a security or governance alert from the engine_mcp_audit_alerts table.
type AuditAlert struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`

	AlertType string `json:"alert_type"`
	Severity  string `json:"severity"`

	Title           string    `json:"title"`
	Description     *string   `json:"description,omitempty"`
	AffectedUserID  *string   `json:"affected_user_id,omitempty"`
	RelatedAuditIDs []uuid.UUID `json:"related_audit_ids,omitempty"`

	Status          string     `json:"status"`
	ResolvedBy      *string    `json:"resolved_by,omitempty"`
	ResolvedAt      *time.Time `json:"resolved_at,omitempty"`
	ResolutionNotes *string    `json:"resolution_notes,omitempty"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// AlertFilters contains filters for querying alerts.
type AlertFilters struct {
	AuditPageFilters
	Status   string // "open", "resolved", "dismissed", or "" for all
	Severity string // "critical", "warning", "info", or "" for all
}

// ValidAlertSeverity returns true if the severity value is valid.
func ValidAlertSeverity(s string) bool {
	switch s {
	case AlertSeverityCritical, AlertSeverityWarning, AlertSeverityInfo:
		return true
	}
	return false
}

// ValidAlertResolution returns true if the resolution status value is valid.
func ValidAlertResolution(s string) bool {
	switch s {
	case AlertStatusResolved, AlertStatusDismissed:
		return true
	}
	return false
}
