package services

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"github.com/ekaya-inc/ekaya-engine/pkg/adapters/datasource"
	"github.com/ekaya-inc/ekaya-engine/pkg/llm"
	"github.com/ekaya-inc/ekaya-engine/pkg/models"
)

const (
	glossaryGenerationStatusPlanning         = "planning"
	glossaryGenerationStatusInvestigating    = "investigating"
	glossaryGenerationStatusQualifying       = "qualifying"
	glossaryGenerationStatusWriting          = "writing"
	glossaryGenerationStatusNoQualifiedTerms = "no_qualified_terms"

	maxGlossaryInvestigationAreas = 12
	maxGlossarySQLAttempts        = 3
	maxGlossaryWritingAttempts    = 2
	maxGlossaryAutoGeneratedTerms = 8
	glossaryTechnicalScoreFloor   = 60
)

var (
	glossaryIntervalPattern = regexp.MustCompile(`(?i)\binterval\s+'(\d+)\s+(day|days|week|weeks|month|months|year|years)'`)
	glossaryDateAddPattern  = regexp.MustCompile(`(?i)\bdateadd\s*\(\s*(day|week|month|year)\s*,\s*(-?\d+)`)
	glossaryDateMathPattern = regexp.MustCompile(`(?i)\b(current_date|current_timestamp|now\(\))\s*-\s*(\d+)\s*(day|days|week|weeks|month|months|year|years)\b`)
	glossaryGeoBoundPattern = regexp.MustCompile(`(?i)\b(latitude|longitude)\b\s*(between|>=|<=|>|<)`)
	glossarySelectPattern   = regexp.MustCompile(`(?is)^\s*select\b`)
	glossaryJoinPairPattern = regexp.MustCompile(`(?i)([a-zA-Z_][\w]*)\.([a-zA-Z_][\w]*)\s*=\s*([a-zA-Z_][\w]*)\.([a-zA-Z_][\w]*)`)
)

type glossaryAutoGenerateContext struct {
	project               *models.Project
	knowledgeFacts        []*models.KnowledgeFact
	tables                []*models.SchemaTable
	tablesByName          map[string]*models.SchemaTable
	schemaColumnsByTable  map[string][]*models.SchemaColumn
	columnMetadataByTable map[string]map[string]*models.ColumnMetadata
	relationships         []glossaryRelationshipEdge
	executor              datasource.QueryExecutor
}

type glossaryInvestigationPlanResponse struct {
	Areas []glossaryInvestigationArea `json:"areas"`
}

type glossaryInvestigationArea struct {
	Rank              int      `json:"rank"`
	Area              string   `json:"area"`
	BusinessRationale string   `json:"business_rationale"`
	Tables            []string `json:"tables"`
	FocusColumns      []string `json:"focus_columns"`
}

type glossaryColumnCandidate struct {
	Table        string
	Column       string
	DataType     string
	Role         string
	SemanticType string
	Description  string
	EnumValues   []string
	NonNullCount int64
	Score        int
}

type glossaryRelationshipEdge struct {
	SourceTable      string
	SourceColumn     string
	TargetTable      string
	TargetColumn     string
	RelationshipType string
	Cardinality      string
	Confidence       float64
}

type glossaryInvestigationEvidence struct {
	Area            glossaryInvestigationArea
	CandidateTables []*models.SchemaTable

	AllowedRelationships []glossaryRelationshipEdge
	MeasureColumns       []glossaryColumnCandidate
	StatusColumns        []glossaryColumnCandidate
	TimeColumns          []glossaryColumnCandidate

	RowCounts      map[string]int64
	JoinRowCounts  map[string]int64
	KnowledgeText  string
	EnumValues     map[string][]string
	FocusColumnSet map[string]struct{}
}

type glossarySQLCandidateResponse struct {
	SQL             string   `json:"sql"`
	BaseTable       string   `json:"base_table"`
	MetricRationale string   `json:"metric_rationale"`
	UsedTables      []string `json:"used_tables"`
}

type glossaryWriteResponse struct {
	Term       string   `json:"term"`
	Definition string   `json:"definition"`
	Aliases    []string `json:"aliases"`
}

type glossaryQualifiedCandidate struct {
	Area              glossaryInvestigationArea
	SQL               string
	BaseTable         string
	OutputColumns     []models.OutputColumn
	ReferencedTables  []string
	TechnicalScore    int
	PresentationScore int
	FinalScore        int
	Attempt           int
	Term              string
	Definition        string
	Aliases           []string
}

type glossaryQualificationResult struct {
	referencedTables []string
	technicalScore   int
}

func isGlossaryGenerationInProgress(status string) bool {
	switch status {
	case glossaryGenerationStatusPlanning,
		glossaryGenerationStatusInvestigating,
		glossaryGenerationStatusQualifying,
		glossaryGenerationStatusWriting:
		return true
	default:
		return false
	}
}

func (s *glossaryService) runSQLFirstAutoGenerate(ctx context.Context, projectID uuid.UUID, startedAt time.Time) error {
	setGenerationStatus(projectID, glossaryGenerationStatusPlanning, "Resolving tenant context...", "", &startedAt)

	tenantCtx, cleanup, err := s.getTenant(ctx, projectID)
	if err != nil {
		setGenerationStatus(projectID, "failed", "Failed to get tenant context", err.Error(), &startedAt)
		return fmt.Errorf("get tenant context: %w", err)
	}
	defer cleanup()

	tenantCtx = models.WithInferredProvenance(tenantCtx, uuid.Nil)

	autoCtx, err := s.buildGlossaryAutoGenerateContext(tenantCtx, projectID)
	if err != nil {
		setGenerationStatus(projectID, "failed", "Failed to prepare generation context", err.Error(), &startedAt)
		return err
	}
	defer autoCtx.executor.Close()

	llmClient, err := s.llmFactory.CreateForProject(tenantCtx, projectID)
	if err != nil {
		setGenerationStatus(projectID, "failed", "Failed to create LLM client", err.Error(), &startedAt)
		return fmt.Errorf("create LLM client: %w", err)
	}

	existingTerms, err := s.glossaryRepo.GetByProject(tenantCtx, projectID)
	if err != nil {
		setGenerationStatus(projectID, "failed", "Failed to load existing glossary terms", err.Error(), &startedAt)
		return fmt.Errorf("get glossary terms: %w", err)
	}
	existingInferredCount := countGlossaryTermsBySource(existingTerms, models.ProvenanceInferred)

	setGenerationStatus(projectID, glossaryGenerationStatusPlanning, "Planning investigation areas...", "", &startedAt)
	areas, err := s.planGlossaryInvestigationAreas(tenantCtx, llmClient, autoCtx)
	if err != nil {
		setGenerationStatus(projectID, "failed", "Planning failed", err.Error(), &startedAt)
		return err
	}
	if len(areas) == 0 {
		setGenerationStatus(projectID, glossaryGenerationStatusNoQualifiedTerms, s.noQualifiedGlossaryMessage(existingInferredCount), "", &startedAt)
		return nil
	}

	var qualified []*glossaryQualifiedCandidate
	for _, area := range areas {
		setGenerationStatus(projectID, glossaryGenerationStatusInvestigating, fmt.Sprintf("Investigating %s...", area.Area), "", &startedAt)
		evidence, err := s.gatherGlossaryInvestigationEvidence(tenantCtx, autoCtx, area)
		if err != nil {
			s.logger.Warn("Glossary investigation failed",
				zap.String("project_id", projectID.String()),
				zap.String("area", area.Area),
				zap.Error(err))
			continue
		}
		if evidence == nil {
			continue
		}

		setGenerationStatus(projectID, glossaryGenerationStatusQualifying, fmt.Sprintf("Qualifying SQL for %s...", area.Area), "", &startedAt)
		candidate, err := s.qualifyGlossaryArea(tenantCtx, projectID, llmClient, autoCtx, evidence)
		if err != nil {
			s.logger.Warn("Glossary qualification rejected area",
				zap.String("project_id", projectID.String()),
				zap.String("area", area.Area),
				zap.Error(err))
			continue
		}

		setGenerationStatus(projectID, glossaryGenerationStatusWriting, fmt.Sprintf("Writing glossary term for %s...", area.Area), "", &startedAt)
		s.populateGlossaryWriteResult(tenantCtx, llmClient, autoCtx, evidence, candidate)
		qualified = append(qualified, candidate)
	}

	qualified = s.filterConflictingQualifiedCandidates(existingTerms, qualified)
	if len(qualified) == 0 {
		setGenerationStatus(projectID, glossaryGenerationStatusNoQualifiedTerms, s.noQualifiedGlossaryMessage(existingInferredCount), "", &startedAt)
		return nil
	}

	sort.SliceStable(qualified, func(i, j int) bool {
		if qualified[i].FinalScore == qualified[j].FinalScore {
			return qualified[i].Area.Rank < qualified[j].Area.Rank
		}
		return qualified[i].FinalScore > qualified[j].FinalScore
	})
	if len(qualified) > maxGlossaryAutoGeneratedTerms {
		qualified = qualified[:maxGlossaryAutoGeneratedTerms]
	}

	terms := make([]*models.BusinessGlossaryTerm, 0, len(qualified))
	for _, candidate := range qualified {
		terms = append(terms, &models.BusinessGlossaryTerm{
			ProjectID:        projectID,
			Term:             candidate.Term,
			Definition:       candidate.Definition,
			DefiningSQL:      candidate.SQL,
			BaseTable:        candidate.BaseTable,
			OutputColumns:    candidate.OutputColumns,
			Aliases:          uniqueStrings(candidate.Aliases),
			EnrichmentStatus: models.GlossaryEnrichmentSuccess,
			Source:           models.ProvenanceInferred,
		})
	}

	if err := s.glossaryRepo.ReplaceInferredTerms(tenantCtx, projectID, terms); err != nil {
		setGenerationStatus(projectID, "failed", "Failed to persist inferred glossary terms", err.Error(), &startedAt)
		return fmt.Errorf("replace inferred glossary terms: %w", err)
	}

	setGenerationStatus(projectID, "completed", fmt.Sprintf("Generated %d verified glossary terms", len(terms)), "", &startedAt)
	return nil
}

func (s *glossaryService) buildGlossaryAutoGenerateContext(ctx context.Context, projectID uuid.UUID) (*glossaryAutoGenerateContext, error) {
	project, err := s.projectService.GetByID(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}

	tables, err := s.schemaRepo.ListTablesByDatasource(ctx, projectID, uuid.Nil)
	if err != nil {
		return nil, fmt.Errorf("get tables: %w", err)
	}
	if len(tables) == 0 {
		return nil, fmt.Errorf("no selected tables found for glossary generation")
	}

	tableNames := make([]string, 0, len(tables))
	tablesByName := make(map[string]*models.SchemaTable, len(tables))
	for _, table := range tables {
		tableNames = append(tableNames, table.TableName)
		tablesByName[strings.ToLower(table.TableName)] = table
	}

	schemaColumnsByTable, err := s.schemaRepo.GetColumnsByTables(ctx, projectID, tableNames)
	if err != nil {
		return nil, fmt.Errorf("get columns by table: %w", err)
	}
	columnMetadataByTable := s.buildColumnMetadataLookup(ctx, projectID, schemaColumnsByTable)

	relationships, err := s.buildGlossaryRelationships(ctx, projectID, tables, schemaColumnsByTable)
	if err != nil {
		return nil, err
	}

	var knowledgeFacts []*models.KnowledgeFact
	if s.knowledgeRepo != nil {
		knowledgeFacts, err = s.knowledgeRepo.GetByProject(ctx, projectID)
		if err != nil {
			s.logger.Warn("Failed to load project knowledge for glossary generation",
				zap.String("project_id", projectID.String()),
				zap.Error(err))
		}
	}

	executor, err := s.newGlossaryQueryExecutor(ctx, projectID)
	if err != nil {
		return nil, err
	}

	return &glossaryAutoGenerateContext{
		project:               project,
		knowledgeFacts:        knowledgeFacts,
		tables:                tables,
		tablesByName:          tablesByName,
		schemaColumnsByTable:  schemaColumnsByTable,
		columnMetadataByTable: columnMetadataByTable,
		relationships:         relationships,
		executor:              executor,
	}, nil
}

func (s *glossaryService) buildGlossaryRelationships(
	ctx context.Context,
	projectID uuid.UUID,
	tables []*models.SchemaTable,
	schemaColumnsByTable map[string][]*models.SchemaColumn,
) ([]glossaryRelationshipEdge, error) {
	rels, err := s.schemaRepo.ListRelationshipsByDatasource(ctx, projectID, uuid.Nil)
	if err != nil {
		return nil, fmt.Errorf("list relationships: %w", err)
	}

	tableByID := make(map[uuid.UUID]*models.SchemaTable, len(tables))
	columnByID := make(map[uuid.UUID]*models.SchemaColumn)
	for _, table := range tables {
		tableByID[table.ID] = table
	}
	for _, columns := range schemaColumnsByTable {
		for _, column := range columns {
			columnByID[column.ID] = column
		}
	}

	edges := make([]glossaryRelationshipEdge, 0, len(rels))
	for _, rel := range rels {
		if rel.IsApproved != nil && !*rel.IsApproved {
			continue
		}
		sourceTable := tableByID[rel.SourceTableID]
		targetTable := tableByID[rel.TargetTableID]
		sourceColumn := columnByID[rel.SourceColumnID]
		targetColumn := columnByID[rel.TargetColumnID]
		if sourceTable == nil || targetTable == nil || sourceColumn == nil || targetColumn == nil {
			continue
		}
		edges = append(edges, glossaryRelationshipEdge{
			SourceTable:      sourceTable.TableName,
			SourceColumn:     sourceColumn.ColumnName,
			TargetTable:      targetTable.TableName,
			TargetColumn:     targetColumn.ColumnName,
			RelationshipType: rel.RelationshipType,
			Cardinality:      rel.Cardinality,
			Confidence:       rel.Confidence,
		})
	}

	return edges, nil
}

func (s *glossaryService) newGlossaryQueryExecutor(ctx context.Context, projectID uuid.UUID) (datasource.QueryExecutor, error) {
	datasources, err := s.datasourceSvc.List(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("failed to list datasources: %w", err)
	}
	if len(datasources) == 0 {
		return nil, fmt.Errorf("no datasource configured for project")
	}

	ds := datasources[0]
	if ds.DecryptionFailed {
		return nil, fmt.Errorf("datasource credentials were encrypted with a different key")
	}

	executor, err := s.adapterFactory.NewQueryExecutor(ctx, ds.DatasourceType, ds.Config, projectID, ds.ID, "")
	if err != nil {
		return nil, fmt.Errorf("failed to create query executor: %w", err)
	}

	return executor, nil
}

func (s *glossaryService) planGlossaryInvestigationAreas(
	ctx context.Context,
	llmClient llm.LLMClient,
	autoCtx *glossaryAutoGenerateContext,
) ([]glossaryInvestigationArea, error) {
	result, err := llmClient.GenerateResponse(ctx, s.buildGlossaryInvestigationPlanPrompt(autoCtx), s.glossaryInvestigationPlannerSystemMessage(), 0.2, false)
	if err != nil {
		return nil, fmt.Errorf("plan investigation areas: %w", err)
	}

	parsed, err := llm.ParseJSONResponse[glossaryInvestigationPlanResponse](result.Content)
	if err != nil {
		s.logger.Warn("Glossary planner response could not be parsed, falling back to deterministic areas", zap.Error(err))
	}

	areas := sanitizeGlossaryInvestigationAreas(parsed.Areas, autoCtx.tablesByName)
	fallback := s.fallbackGlossaryInvestigationAreas(autoCtx)
	seen := make(map[string]bool)
	merged := make([]glossaryInvestigationArea, 0, maxGlossaryInvestigationAreas)

	for _, area := range append(areas, fallback...) {
		key := strings.ToLower(strings.TrimSpace(area.Area))
		if key == "" || seen[key] {
			continue
		}
		seen[key] = true
		merged = append(merged, area)
		if len(merged) == maxGlossaryInvestigationAreas {
			break
		}
	}

	for i := range merged {
		merged[i].Rank = i + 1
	}

	return merged, nil
}

func sanitizeGlossaryInvestigationAreas(areas []glossaryInvestigationArea, tablesByName map[string]*models.SchemaTable) []glossaryInvestigationArea {
	sort.SliceStable(areas, func(i, j int) bool {
		switch {
		case areas[i].Rank == 0 && areas[j].Rank == 0:
			return areas[i].Area < areas[j].Area
		case areas[i].Rank == 0:
			return false
		case areas[j].Rank == 0:
			return true
		default:
			return areas[i].Rank < areas[j].Rank
		}
	})

	clean := make([]glossaryInvestigationArea, 0, len(areas))
	for _, area := range areas {
		area.Area = strings.TrimSpace(area.Area)
		area.BusinessRationale = strings.TrimSpace(area.BusinessRationale)
		if area.Area == "" {
			continue
		}
		area.Tables = filterExistingGlossaryTables(area.Tables, tablesByName)
		area.FocusColumns = uniqueStrings(trimmedStrings(area.FocusColumns))
		clean = append(clean, area)
	}

	return clean
}

func filterExistingGlossaryTables(names []string, tablesByName map[string]*models.SchemaTable) []string {
	var filtered []string
	for _, name := range names {
		trimmed := strings.TrimSpace(name)
		if trimmed == "" {
			continue
		}
		if table := tablesByName[strings.ToLower(trimmed)]; table != nil {
			filtered = append(filtered, table.TableName)
		}
	}
	return uniqueStrings(filtered)
}

func trimmedStrings(values []string) []string {
	trimmed := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			trimmed = append(trimmed, value)
		}
	}
	return trimmed
}

func (s *glossaryService) fallbackGlossaryInvestigationAreas(autoCtx *glossaryAutoGenerateContext) []glossaryInvestigationArea {
	type scoredTable struct {
		table *models.SchemaTable
		score int
	}
	scored := make([]scoredTable, 0, len(autoCtx.tables))
	for _, table := range autoCtx.tables {
		score := 0
		for _, column := range autoCtx.schemaColumnsByTable[table.TableName] {
			meta := autoCtx.columnMetadataByTable[table.TableName][column.ColumnName]
			switch {
			case glossaryMeasureColumnScore(column, meta) > 0:
				score += 5
			case glossaryTimeColumnScore(column, meta) > 0:
				score += 3
			case glossaryStatusColumnScore(column, meta) > 0:
				score += 2
			}
		}
		if table.RowCount != nil && *table.RowCount > 0 {
			score += 5
		}
		scored = append(scored, scoredTable{table: table, score: score})
	}

	sort.SliceStable(scored, func(i, j int) bool {
		if scored[i].score == scored[j].score {
			return scored[i].table.TableName < scored[j].table.TableName
		}
		return scored[i].score > scored[j].score
	})

	var areas []glossaryInvestigationArea
	for idx, item := range scored {
		if item.score == 0 || idx == maxGlossaryInvestigationAreas {
			break
		}
		areas = append(areas, glossaryInvestigationArea{
			Rank:              idx + 1,
			Area:              humanizeIdentifier(item.table.TableName) + " Metrics",
			BusinessRationale: "This table has strong populated measure, status, or time signals for a reliable aggregate metric.",
			Tables:            []string{item.table.TableName},
		})
	}

	return areas
}

func (s *glossaryService) gatherGlossaryInvestigationEvidence(
	ctx context.Context,
	autoCtx *glossaryAutoGenerateContext,
	area glossaryInvestigationArea,
) (*glossaryInvestigationEvidence, error) {
	candidateTables := s.selectGlossaryCandidateTables(autoCtx, area)
	if len(candidateTables) == 0 {
		return nil, nil
	}

	rowCounts := make(map[string]int64, len(candidateTables))
	for _, table := range candidateTables {
		rowCount, err := s.probeGlossaryTableRowCount(ctx, autoCtx, table)
		if err != nil {
			return nil, err
		}
		rowCounts[table.TableName] = rowCount
	}

	measureColumns := make([]glossaryColumnCandidate, 0)
	statusColumns := make([]glossaryColumnCandidate, 0)
	timeColumns := make([]glossaryColumnCandidate, 0)
	enumValues := make(map[string][]string)
	focusSet := make(map[string]struct{})
	for _, focusColumn := range area.FocusColumns {
		focusSet[strings.ToLower(focusColumn)] = struct{}{}
	}

	for _, table := range candidateTables {
		for _, column := range autoCtx.schemaColumnsByTable[table.TableName] {
			meta := autoCtx.columnMetadataByTable[table.TableName][column.ColumnName]
			candidate := glossaryColumnCandidate{
				Table:        table.TableName,
				Column:       column.ColumnName,
				DataType:     column.DataType,
				EnumValues:   glossaryEnumValues(column, meta),
				Role:         glossaryColumnRole(meta),
				SemanticType: glossaryColumnSemanticType(meta),
				Description:  glossaryColumnDescription(meta),
			}
			if len(candidate.EnumValues) > 0 {
				enumValues[glossaryColumnKey(candidate.Table, candidate.Column)] = candidate.EnumValues
			}

			switch {
			case glossaryMeasureColumnScore(column, meta) > 0:
				measureColumns = append(measureColumns, candidate)
			case glossaryStatusColumnScore(column, meta) > 0:
				statusColumns = append(statusColumns, candidate)
			case glossaryTimeColumnScore(column, meta) > 0:
				timeColumns = append(timeColumns, candidate)
			}
		}
	}

	measureColumns = s.enrichGlossaryColumnSupport(ctx, autoCtx, candidateTables, measureColumns, 6)
	statusColumns = s.enrichGlossaryColumnSupport(ctx, autoCtx, candidateTables, statusColumns, 4)
	timeColumns = s.enrichGlossaryColumnSupport(ctx, autoCtx, candidateTables, timeColumns, 4)

	if len(measureColumns) == 0 && len(statusColumns) == 0 {
		return nil, nil
	}

	allowedRelationships := glossaryAllowedRelationships(autoCtx.relationships, candidateTables)
	joinCounts, err := s.probeGlossaryJoinCounts(ctx, autoCtx, allowedRelationships)
	if err != nil {
		return nil, err
	}

	return &glossaryInvestigationEvidence{
		Area:                 area,
		CandidateTables:      candidateTables,
		AllowedRelationships: allowedRelationships,
		MeasureColumns:       measureColumns,
		StatusColumns:        statusColumns,
		TimeColumns:          timeColumns,
		RowCounts:            rowCounts,
		JoinRowCounts:        joinCounts,
		KnowledgeText:        glossaryKnowledgeText(autoCtx.project, autoCtx.knowledgeFacts),
		EnumValues:           enumValues,
		FocusColumnSet:       focusSet,
	}, nil
}

func (s *glossaryService) selectGlossaryCandidateTables(autoCtx *glossaryAutoGenerateContext, area glossaryInvestigationArea) []*models.SchemaTable {
	selected := make([]*models.SchemaTable, 0, 4)
	seen := make(map[string]bool)
	addTable := func(table *models.SchemaTable) {
		if table == nil {
			return
		}
		key := strings.ToLower(table.TableName)
		if seen[key] {
			return
		}
		seen[key] = true
		selected = append(selected, table)
	}

	for _, tableName := range area.Tables {
		addTable(autoCtx.tablesByName[strings.ToLower(tableName)])
	}

	if len(selected) == 0 {
		type scoredTable struct {
			table *models.SchemaTable
			score int
		}
		var scored []scoredTable
		needle := strings.ToLower(area.Area + " " + area.BusinessRationale + " " + strings.Join(area.FocusColumns, " "))
		for _, table := range autoCtx.tables {
			score := glossaryAreaTableScore(needle, table, autoCtx.schemaColumnsByTable[table.TableName])
			if score > 0 {
				scored = append(scored, scoredTable{table: table, score: score})
			}
		}
		sort.SliceStable(scored, func(i, j int) bool {
			if scored[i].score == scored[j].score {
				return scored[i].table.TableName < scored[j].table.TableName
			}
			return scored[i].score > scored[j].score
		})
		for _, item := range scored {
			addTable(item.table)
			if len(selected) == 3 {
				break
			}
		}
	}

	for _, edge := range autoCtx.relationships {
		if len(selected) >= 4 {
			break
		}
		if seen[strings.ToLower(edge.SourceTable)] && !seen[strings.ToLower(edge.TargetTable)] {
			addTable(autoCtx.tablesByName[strings.ToLower(edge.TargetTable)])
		}
		if seen[strings.ToLower(edge.TargetTable)] && !seen[strings.ToLower(edge.SourceTable)] {
			addTable(autoCtx.tablesByName[strings.ToLower(edge.SourceTable)])
		}
	}

	return selected
}

func glossaryAreaTableScore(needle string, table *models.SchemaTable, columns []*models.SchemaColumn) int {
	score := 0
	tableName := strings.ToLower(table.TableName)
	if strings.Contains(needle, tableName) {
		score += 12
	}
	for _, token := range strings.Fields(needle) {
		if len(token) < 3 {
			continue
		}
		if strings.Contains(tableName, token) {
			score += 6
		}
		for _, column := range columns {
			if strings.Contains(strings.ToLower(column.ColumnName), token) {
				score += 2
			}
		}
	}
	return score
}

func (s *glossaryService) enrichGlossaryColumnSupport(
	ctx context.Context,
	autoCtx *glossaryAutoGenerateContext,
	tables []*models.SchemaTable,
	columns []glossaryColumnCandidate,
	limit int,
) []glossaryColumnCandidate {
	if len(columns) == 0 {
		return nil
	}

	sort.SliceStable(columns, func(i, j int) bool {
		if columns[i].Score == columns[j].Score {
			if columns[i].Table == columns[j].Table {
				return columns[i].Column < columns[j].Column
			}
			return columns[i].Table < columns[j].Table
		}
		return columns[i].Score > columns[j].Score
	})
	if len(columns) > limit {
		columns = columns[:limit]
	}

	for i := range columns {
		count, err := s.probeGlossaryColumnNonNullCount(ctx, autoCtx, autoCtx.tablesByName[strings.ToLower(columns[i].Table)], columns[i].Column)
		if err != nil {
			s.logger.Warn("Failed to probe glossary column support",
				zap.String("table", columns[i].Table),
				zap.String("column", columns[i].Column),
				zap.Error(err))
			continue
		}
		columns[i].NonNullCount = count
		columns[i].Score += glossarySupportScore(count)
	}

	sort.SliceStable(columns, func(i, j int) bool {
		if columns[i].Score == columns[j].Score {
			if columns[i].Table == columns[j].Table {
				return columns[i].Column < columns[j].Column
			}
			return columns[i].Table < columns[j].Table
		}
		return columns[i].Score > columns[j].Score
	})
	return columns
}

func glossarySupportScore(nonNullCount int64) int {
	switch {
	case nonNullCount > 1000:
		return 5
	case nonNullCount > 100:
		return 4
	case nonNullCount > 10:
		return 3
	case nonNullCount > 0:
		return 2
	default:
		return 0
	}
}

func glossaryAllowedRelationships(all []glossaryRelationshipEdge, tables []*models.SchemaTable) []glossaryRelationshipEdge {
	tableSet := make(map[string]bool, len(tables))
	for _, table := range tables {
		tableSet[strings.ToLower(table.TableName)] = true
	}

	var allowed []glossaryRelationshipEdge
	for _, edge := range all {
		if tableSet[strings.ToLower(edge.SourceTable)] && tableSet[strings.ToLower(edge.TargetTable)] {
			allowed = append(allowed, edge)
		}
	}

	return allowed
}

func (s *glossaryService) probeGlossaryTableRowCount(
	ctx context.Context,
	autoCtx *glossaryAutoGenerateContext,
	table *models.SchemaTable,
) (int64, error) {
	if table.RowCount != nil {
		return *table.RowCount, nil
	}

	result, err := autoCtx.executor.Query(ctx, fmt.Sprintf("SELECT COUNT(*) AS row_count FROM %s", glossaryQuotedTableRef(autoCtx.executor, table)), 1)
	if err != nil {
		return 0, fmt.Errorf("count rows for %s: %w", table.TableName, err)
	}

	return glossaryReadFirstInt(result), nil
}

func (s *glossaryService) probeGlossaryColumnNonNullCount(
	ctx context.Context,
	autoCtx *glossaryAutoGenerateContext,
	table *models.SchemaTable,
	column string,
) (int64, error) {
	query := fmt.Sprintf(
		"SELECT COUNT(%s) AS non_null_count FROM %s",
		autoCtx.executor.QuoteIdentifier(column),
		glossaryQuotedTableRef(autoCtx.executor, table),
	)
	result, err := autoCtx.executor.Query(ctx, query, 1)
	if err != nil {
		return 0, fmt.Errorf("count non-null values for %s.%s: %w", table.TableName, column, err)
	}

	return glossaryReadFirstInt(result), nil
}

func (s *glossaryService) probeGlossaryJoinCounts(
	ctx context.Context,
	autoCtx *glossaryAutoGenerateContext,
	edges []glossaryRelationshipEdge,
) (map[string]int64, error) {
	joinCounts := make(map[string]int64, len(edges))
	for _, edge := range edges {
		sourceTable := autoCtx.tablesByName[strings.ToLower(edge.SourceTable)]
		targetTable := autoCtx.tablesByName[strings.ToLower(edge.TargetTable)]
		if sourceTable == nil || targetTable == nil {
			continue
		}
		query := fmt.Sprintf(
			"SELECT COUNT(*) AS join_count FROM %s s JOIN %s t ON s.%s = t.%s",
			glossaryQuotedTableRef(autoCtx.executor, sourceTable),
			glossaryQuotedTableRef(autoCtx.executor, targetTable),
			autoCtx.executor.QuoteIdentifier(edge.SourceColumn),
			autoCtx.executor.QuoteIdentifier(edge.TargetColumn),
		)
		result, err := autoCtx.executor.Query(ctx, query, 1)
		if err != nil {
			return nil, fmt.Errorf("probe join count for %s.%s -> %s.%s: %w", edge.SourceTable, edge.SourceColumn, edge.TargetTable, edge.TargetColumn, err)
		}
		joinCounts[glossaryRelationshipKey(edge)] = glossaryReadFirstInt(result)
	}

	return joinCounts, nil
}

func glossaryQuotedTableRef(executor datasource.QueryExecutor, table *models.SchemaTable) string {
	if table.SchemaName != "" {
		return executor.QuoteIdentifier(table.SchemaName) + "." + executor.QuoteIdentifier(table.TableName)
	}
	return executor.QuoteIdentifier(table.TableName)
}

func glossaryReadFirstInt(result *datasource.QueryExecutionResult) int64 {
	if result == nil || len(result.Rows) == 0 {
		return 0
	}
	for _, value := range result.Rows[0] {
		return glossaryToInt64(value)
	}
	return 0
}

func glossaryToInt64(value any) int64 {
	switch v := value.(type) {
	case int:
		return int64(v)
	case int32:
		return int64(v)
	case int64:
		return v
	case float64:
		return int64(v)
	case string:
		n, _ := strconv.ParseInt(v, 10, 64)
		return n
	case []byte:
		n, _ := strconv.ParseInt(string(v), 10, 64)
		return n
	default:
		return 0
	}
}

func (s *glossaryService) qualifyGlossaryArea(
	ctx context.Context,
	projectID uuid.UUID,
	llmClient llm.LLMClient,
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
) (*glossaryQualifiedCandidate, error) {
	var lastErr error
	for attempt := 1; attempt <= maxGlossarySQLAttempts; attempt++ {
		sqlCandidate, err := s.generateGlossarySQLCandidate(ctx, llmClient, autoCtx, evidence, attempt, lastErr)
		if err != nil {
			lastErr = err
			continue
		}

		testResult, err := s.TestSQL(ctx, projectID, sqlCandidate.SQL)
		if err != nil {
			lastErr = fmt.Errorf("test SQL: %w", err)
			continue
		}
		if !testResult.Valid {
			lastErr = fmt.Errorf("SQL validation failed: %s", testResult.Error)
			continue
		}
		if testResult.SampleRow == nil {
			lastErr = fmt.Errorf("SQL must return exactly one row")
			continue
		}

		if errs := validateColumnReferences(sqlCandidate.SQL, autoCtx.schemaColumnsByTable); len(errs) > 0 {
			lastErr = fmt.Errorf("%s", formatColumnValidationError(errs))
			continue
		}

		qualification, err := s.qualifyGlossarySQL(autoCtx, evidence, sqlCandidate, testResult, attempt)
		if err != nil {
			lastErr = err
			continue
		}

		baseTable := sqlCandidate.BaseTable
		if baseTable == "" && len(sqlCandidate.UsedTables) > 0 {
			baseTable = sqlCandidate.UsedTables[0]
		}
		if baseTable == "" {
			baseTable = evidence.CandidateTables[0].TableName
		}

		return &glossaryQualifiedCandidate{
			Area:             evidence.Area,
			SQL:              sqlCandidate.SQL,
			BaseTable:        baseTable,
			OutputColumns:    testResult.OutputColumns,
			ReferencedTables: qualification.referencedTables,
			TechnicalScore:   qualification.technicalScore,
			Attempt:          attempt,
		}, nil
	}

	if lastErr == nil {
		lastErr = fmt.Errorf("no SQL candidate qualified")
	}
	return nil, lastErr
}

func (s *glossaryService) generateGlossarySQLCandidate(
	ctx context.Context,
	llmClient llm.LLMClient,
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	attempt int,
	lastErr error,
) (*glossarySQLCandidateResponse, error) {
	prompt := s.buildGlossarySQLCandidatePrompt(autoCtx, evidence, attempt, lastErr)
	result, err := llmClient.GenerateResponse(ctx, prompt, s.glossarySQLCandidateSystemMessage(), 0.2, false)
	if err != nil {
		return nil, fmt.Errorf("generate SQL candidate: %w", err)
	}

	parsed, err := llm.ParseJSONResponse[glossarySQLCandidateResponse](result.Content)
	if err != nil {
		return nil, fmt.Errorf("parse SQL candidate: %w", err)
	}
	parsed.SQL = strings.TrimSpace(parsed.SQL)
	parsed.BaseTable = strings.TrimSpace(parsed.BaseTable)
	parsed.UsedTables = uniqueStrings(trimmedStrings(parsed.UsedTables))

	if parsed.SQL == "" {
		return nil, fmt.Errorf("SQL candidate was empty")
	}

	return &parsed, nil
}

func (s *glossaryService) qualifyGlossarySQL(
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	sqlCandidate *glossarySQLCandidateResponse,
	testResult *SQLTestResult,
	attempt int,
) (*glossaryQualificationResult, error) {
	sqlText := strings.TrimSpace(sqlCandidate.SQL)
	if !glossarySelectPattern.MatchString(sqlText) {
		return nil, fmt.Errorf("glossary SQL must be a single SELECT statement")
	}
	if strings.Contains(sqlText, ";") {
		return nil, fmt.Errorf("glossary SQL must be a single self-contained SELECT")
	}

	referencedTables := glossaryExtractReferencedTables(sqlText, autoCtx.tablesByName)
	if len(referencedTables) == 0 {
		return nil, fmt.Errorf("SQL must reference at least one known table")
	}

	if err := glossaryValidateUsedTables(referencedTables, evidence.CandidateTables); err != nil {
		return nil, err
	}
	if err := glossaryValidateJoinPolicy(sqlText, evidence); err != nil {
		return nil, err
	}
	if err := glossaryValidateHiddenParameters(sqlText, evidence.KnowledgeText); err != nil {
		return nil, err
	}
	if err := glossaryValidateConventions(sqlText, autoCtx, evidence, referencedTables); err != nil {
		return nil, err
	}
	if warnings := ValidateFormulaSemantics(humanizeIdentifier(evidence.Area.Area), sqlText); len(warnings) > 0 {
		return nil, fmt.Errorf("%s", warnings[0].Message)
	}

	technicalScore := glossaryScoreTechnicalCandidate(sqlText, evidence, referencedTables, attempt)
	if technicalScore < glossaryTechnicalScoreFloor {
		return nil, fmt.Errorf("technical score %d is below qualification threshold", technicalScore)
	}

	// Reject semantically empty metrics that only work over empty inputs.
	if glossaryAllValuesNull(testResult.SampleRow) && !glossaryEvidenceHasPopulatedPath(evidence) {
		return nil, fmt.Errorf("query result is degenerate because the underlying data path is empty")
	}

	return &glossaryQualificationResult{
		referencedTables: referencedTables,
		technicalScore:   technicalScore,
	}, nil
}

func glossaryValidateUsedTables(referencedTables []string, candidateTables []*models.SchemaTable) error {
	allowed := make(map[string]bool, len(candidateTables))
	for _, table := range candidateTables {
		allowed[strings.ToLower(table.TableName)] = true
	}
	for _, table := range referencedTables {
		if !allowed[strings.ToLower(table)] {
			return fmt.Errorf("SQL referenced table %q outside the allowed investigation scope", table)
		}
	}
	return nil
}

func glossaryValidateJoinPolicy(sqlText string, evidence *glossaryInvestigationEvidence) error {
	lowerSQL := strings.ToLower(sqlText)
	if !strings.Contains(lowerSQL, " join ") {
		return nil
	}
	if len(evidence.AllowedRelationships) == 0 {
		return fmt.Errorf("SQL uses joins but the investigation area has no documented relationship path")
	}

	aliases := extractTableAliases(sqlText, glossarySchemaColumnsByTableSubset(evidence))
	pairs := glossaryJoinPairPattern.FindAllStringSubmatch(sqlText, -1)
	if len(pairs) == 0 {
		return fmt.Errorf("SQL join conditions must use documented table relationships")
	}

	allowedPairs := make(map[string]bool)
	for _, edge := range evidence.AllowedRelationships {
		allowedPairs[glossaryJoinPairKey(edge.SourceTable, edge.SourceColumn, edge.TargetTable, edge.TargetColumn)] = true
		allowedPairs[glossaryJoinPairKey(edge.TargetTable, edge.TargetColumn, edge.SourceTable, edge.SourceColumn)] = true
	}

	for _, pair := range pairs {
		leftTable := glossaryResolveAlias(pair[1], aliases)
		rightTable := glossaryResolveAlias(pair[3], aliases)
		if leftTable == "" || rightTable == "" || leftTable == rightTable {
			continue
		}
		key := glossaryJoinPairKey(leftTable, pair[2], rightTable, pair[4])
		if !allowedPairs[key] {
			return fmt.Errorf("join path %s.%s = %s.%s is not a documented relationship", leftTable, pair[2], rightTable, pair[4])
		}
	}

	return nil
}

func glossarySchemaColumnsByTableSubset(evidence *glossaryInvestigationEvidence) map[string][]*models.SchemaColumn {
	result := make(map[string][]*models.SchemaColumn, len(evidence.CandidateTables))
	for _, table := range evidence.CandidateTables {
		result[table.TableName] = nil
	}
	return result
}

func glossaryResolveAlias(alias string, aliases map[string]string) string {
	if table, ok := aliases[strings.ToLower(alias)]; ok {
		return table
	}
	return strings.ToLower(alias)
}

func glossaryJoinPairKey(leftTable, leftColumn, rightTable, rightColumn string) string {
	return strings.ToLower(leftTable + "." + leftColumn + "->" + rightTable + "." + rightColumn)
}

func glossaryValidateHiddenParameters(sqlText string, knowledgeText string) error {
	lowerKnowledge := strings.ToLower(knowledgeText)
	if matches := glossaryIntervalPattern.FindStringSubmatch(sqlText); len(matches) == 3 {
		if !strings.Contains(lowerKnowledge, strings.ToLower(matches[1]+" "+matches[2])) {
			return fmt.Errorf("SQL depends on undocumented time window %q", matches[0])
		}
	}
	if matches := glossaryDateAddPattern.FindStringSubmatch(sqlText); len(matches) == 3 {
		window := strings.ToLower(matches[2] + " " + matches[1])
		if !strings.Contains(lowerKnowledge, window) {
			return fmt.Errorf("SQL depends on undocumented time window %q", matches[0])
		}
	}
	if matches := glossaryDateMathPattern.FindStringSubmatch(sqlText); len(matches) == 4 {
		window := strings.ToLower(matches[2] + " " + matches[3])
		if !strings.Contains(lowerKnowledge, window) {
			return fmt.Errorf("SQL depends on undocumented time window %q", matches[0])
		}
	}
	if glossaryGeoBoundPattern.MatchString(sqlText) && !strings.Contains(lowerKnowledge, "latitude") && !strings.Contains(lowerKnowledge, "longitude") {
		return fmt.Errorf("SQL depends on geographic bounds that are not documented in project knowledge")
	}
	return nil
}

func glossaryValidateConventions(
	sqlText string,
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	referencedTables []string,
) error {
	lowerSQL := strings.ToLower(sqlText)

	if conventions := autoCtx.project.DomainSummary; conventions != nil && conventions.Conventions != nil {
		if softDelete := conventions.Conventions.SoftDelete; softDelete != nil && softDelete.Enabled {
			expectedColumn := strings.ToLower(softDelete.Column)
			for _, tableName := range referencedTables {
				if glossaryTableHasColumn(autoCtx.schemaColumnsByTable[tableName], expectedColumn) {
					if !glossaryContainsSoftDeleteFilter(lowerSQL, expectedColumn, strings.ToLower(softDelete.Filter)) {
						return fmt.Errorf("SQL omitted the required soft-delete convention for %s", tableName)
					}
				}
			}
		}
	}

	for _, measure := range evidence.MeasureColumns {
		key := glossaryColumnKey(measure.Table, measure.Column)
		if !strings.Contains(lowerSQL, strings.ToLower(measure.Column)) {
			continue
		}
		if measure.SemanticType == "currency_cents" || strings.HasSuffix(strings.ToLower(measure.Column), "_cents") {
			if !glossaryContainsDivision(lowerSQL, 100) {
				return fmt.Errorf("SQL referenced monetary column %s without currency normalization", key)
			}
		}
		if measure.SemanticType == "basis_points" || strings.HasSuffix(strings.ToLower(measure.Column), "_bps") {
			if !glossaryContainsDivision(lowerSQL, 10000) {
				return fmt.Errorf("SQL referenced basis-point column %s without normalization", key)
			}
		}
	}

	return nil
}

func glossaryContainsSoftDeleteFilter(lowerSQL, columnName, fallbackFilter string) bool {
	if strings.Contains(lowerSQL, fallbackFilter) {
		return true
	}
	return strings.Contains(lowerSQL, columnName+" is null") ||
		strings.Contains(lowerSQL, columnName+" = false") ||
		strings.Contains(lowerSQL, columnName+"=false")
}

func glossaryTableHasColumn(columns []*models.SchemaColumn, expected string) bool {
	for _, column := range columns {
		if strings.EqualFold(column.ColumnName, expected) {
			return true
		}
	}
	return false
}

func glossaryContainsDivision(lowerSQL string, divisor int) bool {
	divisorStr := strconv.Itoa(divisor)
	return strings.Contains(lowerSQL, "/"+divisorStr) ||
		strings.Contains(lowerSQL, "/ "+divisorStr) ||
		strings.Contains(lowerSQL, "* 0.01") ||
		strings.Contains(lowerSQL, "*0.01") ||
		strings.Contains(lowerSQL, "* 0.0001") ||
		strings.Contains(lowerSQL, "*0.0001")
}

func glossaryExtractReferencedTables(sqlText string, tablesByName map[string]*models.SchemaTable) []string {
	tokens := tokenizeSQL(sqlText)
	var tables []string
	seen := make(map[string]bool)
	for i := 0; i < len(tokens); i++ {
		token := strings.ToLower(tokens[i])
		if token != "from" && token != "join" {
			continue
		}
		if i+1 >= len(tokens) {
			continue
		}
		next := strings.ToLower(tokens[i+1])
		if i+3 < len(tokens) && tokens[i+2] == "." {
			next = strings.ToLower(tokens[i+3])
		}
		if table := tablesByName[next]; table != nil && !seen[next] {
			seen[next] = true
			tables = append(tables, table.TableName)
		}
	}
	return tables
}

func glossaryAllValuesNull(sampleRow map[string]interface{}) bool {
	if len(sampleRow) == 0 {
		return true
	}
	for _, value := range sampleRow {
		if value != nil {
			switch typed := value.(type) {
			case string:
				if strings.TrimSpace(typed) != "" {
					return false
				}
			default:
				return false
			}
		}
	}
	return true
}

func glossaryEvidenceHasPopulatedPath(evidence *glossaryInvestigationEvidence) bool {
	for _, rowCount := range evidence.RowCounts {
		if rowCount > 0 {
			return true
		}
	}
	for _, joinCount := range evidence.JoinRowCounts {
		if joinCount > 0 {
			return true
		}
	}
	for _, column := range evidence.MeasureColumns {
		if column.NonNullCount > 0 {
			return true
		}
	}
	return false
}

func glossaryScoreTechnicalCandidate(sqlText string, evidence *glossaryInvestigationEvidence, referencedTables []string, attempt int) int {
	score := 0

	priorityScore := 20 - (evidence.Area.Rank-1)*2
	if priorityScore < 4 {
		priorityScore = 4
	}
	score += priorityScore

	joinCount := strings.Count(strings.ToLower(sqlText), " join ")
	switch {
	case joinCount == 0:
		score += 20
	case joinCount == 1:
		score += 17
	case joinCount == 2:
		score += 14
	default:
		score += 10
	}

	semanticScore := 0
	if glossaryReferencesAnyColumn(sqlText, evidence.MeasureColumns) {
		semanticScore += 8
	}
	if glossaryReferencesAnyColumn(sqlText, evidence.StatusColumns) {
		semanticScore += 6
	}
	if glossaryReferencesAnyColumn(sqlText, evidence.TimeColumns) {
		semanticScore += 6
	}
	score += semanticScore

	dataScore := 0
	for _, table := range referencedTables {
		if evidence.RowCounts[table] > 0 {
			dataScore += 4
		}
	}
	if glossaryHasNonNullMeasure(evidence) {
		dataScore += 8
	}
	if joinCount == 0 || glossaryHasJoinSupport(evidence) {
		dataScore += 8
	}
	if dataScore > 20 {
		dataScore = 20
	}
	score += dataScore

	switch attempt {
	case 1:
		score += 10
	case 2:
		score += 7
	default:
		score += 4
	}

	return score
}

func glossaryReferencesAnyColumn(sqlText string, columns []glossaryColumnCandidate) bool {
	lowerSQL := strings.ToLower(sqlText)
	for _, column := range columns {
		if strings.Contains(lowerSQL, strings.ToLower(column.Column)) {
			return true
		}
	}
	return false
}

func glossaryHasNonNullMeasure(evidence *glossaryInvestigationEvidence) bool {
	for _, column := range evidence.MeasureColumns {
		if column.NonNullCount > 0 {
			return true
		}
	}
	return false
}

func glossaryHasJoinSupport(evidence *glossaryInvestigationEvidence) bool {
	for _, joinCount := range evidence.JoinRowCounts {
		if joinCount > 0 {
			return true
		}
	}
	return false
}

func (s *glossaryService) populateGlossaryWriteResult(
	ctx context.Context,
	llmClient llm.LLMClient,
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	candidate *glossaryQualifiedCandidate,
) {
	for attempt := 1; attempt <= maxGlossaryWritingAttempts; attempt++ {
		result, err := llmClient.GenerateResponse(ctx, s.buildGlossaryWritePrompt(autoCtx, evidence, candidate), s.glossaryWriteSystemMessage(), 0.2, false)
		if err != nil {
			continue
		}
		parsed, err := llm.ParseJSONResponse[glossaryWriteResponse](result.Content)
		if err != nil {
			continue
		}

		parsed.Term = strings.TrimSpace(parsed.Term)
		parsed.Definition = strings.TrimSpace(parsed.Definition)
		parsed.Aliases = uniqueStrings(trimmedStrings(parsed.Aliases))
		if parsed.Term == "" || parsed.Definition == "" || IsTestTerm(parsed.Term) {
			continue
		}

		candidate.Term = parsed.Term
		candidate.Definition = parsed.Definition
		candidate.Aliases = parsed.Aliases
		candidate.PresentationScore = glossaryScorePresentation(parsed.Term, parsed.Definition)
		candidate.FinalScore = candidate.TechnicalScore + candidate.PresentationScore
		return
	}

	fallbackAlias := ""
	if len(candidate.OutputColumns) > 0 {
		fallbackAlias = humanizeIdentifier(candidate.OutputColumns[0].Name)
	}
	if fallbackAlias == "" {
		fallbackAlias = humanizeIdentifier(evidence.Area.Area)
	}
	candidate.Term = fallbackAlias
	candidate.Definition = fmt.Sprintf("Verified aggregate metric generated from %s using documented schema relationships and current project conventions.", strings.Join(candidate.ReferencedTables, ", "))
	candidate.Aliases = nil
	candidate.PresentationScore = 1
	candidate.FinalScore = candidate.TechnicalScore + candidate.PresentationScore
}

func glossaryScorePresentation(term string, definition string) int {
	score := 0
	words := strings.Fields(term)
	switch {
	case len(words) >= 1 && len(words) <= 4:
		score += 5
	case len(words) <= 6:
		score += 3
	default:
		score += 1
	}

	switch {
	case len(definition) > 80:
		score += 5
	case len(definition) > 40:
		score += 3
	default:
		score += 1
	}

	return score
}

func (s *glossaryService) filterConflictingQualifiedCandidates(
	existingTerms []*models.BusinessGlossaryTerm,
	candidates []*glossaryQualifiedCandidate,
) []*glossaryQualifiedCandidate {
	curatedTerms := make(map[string]bool)
	for _, term := range existingTerms {
		if term.Source != models.ProvenanceInferred {
			curatedTerms[strings.ToLower(term.Term)] = true
		}
	}

	filtered := make([]*glossaryQualifiedCandidate, 0, len(candidates))
	seenTerms := make(map[string]bool)
	for _, candidate := range candidates {
		key := strings.ToLower(strings.TrimSpace(candidate.Term))
		if key == "" || curatedTerms[key] || seenTerms[key] {
			continue
		}
		seenTerms[key] = true
		filtered = append(filtered, candidate)
	}

	return filtered
}

func (s *glossaryService) noQualifiedGlossaryMessage(existingInferredCount int) string {
	if existingInferredCount > 0 {
		return "No new example glossary terms met the quality bar. Existing inferred terms were preserved."
	}
	return "No example glossary terms met the quality bar for this project. Try auto-generate again or add a term manually."
}

func countGlossaryTermsBySource(terms []*models.BusinessGlossaryTerm, source string) int {
	count := 0
	for _, term := range terms {
		if term.Source == source {
			count++
		}
	}
	return count
}

func glossaryKnowledgeText(project *models.Project, knowledgeFacts []*models.KnowledgeFact) string {
	var parts []string
	if project != nil && project.DomainSummary != nil {
		if project.DomainSummary.Description != "" {
			parts = append(parts, project.DomainSummary.Description)
		}
	}
	for _, fact := range knowledgeFacts {
		parts = append(parts, fact.Value)
		if fact.Context != "" {
			parts = append(parts, fact.Context)
		}
	}
	return strings.ToLower(strings.Join(parts, " "))
}

func glossaryColumnKey(table, column string) string {
	return strings.ToLower(table + "." + column)
}

func glossaryRelationshipKey(edge glossaryRelationshipEdge) string {
	return strings.ToLower(edge.SourceTable + "." + edge.SourceColumn + "->" + edge.TargetTable + "." + edge.TargetColumn)
}

func glossaryEnumValues(column *models.SchemaColumn, meta *models.ColumnMetadata) []string {
	if meta != nil {
		if enumFeatures := meta.GetEnumFeatures(); enumFeatures != nil && len(enumFeatures.Values) > 0 {
			values := make([]string, 0, len(enumFeatures.Values))
			for _, value := range enumFeatures.Values {
				values = append(values, value.Value)
			}
			return uniqueStrings(values)
		}
	}
	return uniqueStrings(column.EnumValues)
}

func glossaryColumnRole(meta *models.ColumnMetadata) string {
	if meta == nil || meta.Role == nil {
		return ""
	}
	return *meta.Role
}

func glossaryColumnSemanticType(meta *models.ColumnMetadata) string {
	if meta == nil || meta.SemanticType == nil {
		return ""
	}
	return *meta.SemanticType
}

func glossaryColumnDescription(meta *models.ColumnMetadata) string {
	if meta == nil || meta.Description == nil {
		return ""
	}
	return *meta.Description
}

func glossaryMeasureColumnScore(column *models.SchemaColumn, meta *models.ColumnMetadata) int {
	score := 0
	role := glossaryColumnRole(meta)
	semanticType := strings.ToLower(glossaryColumnSemanticType(meta))
	name := strings.ToLower(column.ColumnName)
	dataType := strings.ToLower(column.DataType)

	if role == "measure" {
		score += 12
	}
	if strings.Contains(semanticType, "currency") || strings.Contains(semanticType, "amount") || strings.Contains(semanticType, "duration") {
		score += 8
	}
	if strings.Contains(name, "amount") || strings.Contains(name, "revenue") || strings.Contains(name, "price") || strings.Contains(name, "cost") || strings.Contains(name, "fee") || strings.Contains(name, "duration") || strings.Contains(name, "total") || strings.Contains(name, "count") || strings.Contains(name, "qty") || strings.Contains(name, "quantity") {
		score += 6
	}
	if strings.Contains(dataType, "int") || strings.Contains(dataType, "numeric") || strings.Contains(dataType, "decimal") || strings.Contains(dataType, "double") || strings.Contains(dataType, "real") {
		score += 4
	}
	return score
}

func glossaryStatusColumnScore(column *models.SchemaColumn, meta *models.ColumnMetadata) int {
	score := 0
	role := glossaryColumnRole(meta)
	name := strings.ToLower(column.ColumnName)
	if role == "dimension" {
		score += 4
	}
	if len(glossaryEnumValues(column, meta)) > 0 {
		score += 8
	}
	if strings.Contains(name, "status") || strings.Contains(name, "state") || strings.Contains(name, "type") {
		score += 5
	}
	return score
}

func glossaryTimeColumnScore(column *models.SchemaColumn, meta *models.ColumnMetadata) int {
	score := 0
	name := strings.ToLower(column.ColumnName)
	semanticType := strings.ToLower(glossaryColumnSemanticType(meta))
	if strings.Contains(semanticType, "time") || strings.Contains(semanticType, "date") {
		score += 8
	}
	if strings.HasSuffix(name, "_at") || strings.HasSuffix(name, "_date") || strings.HasSuffix(name, "_time") || name == "date" || name == "created_at" || name == "updated_at" {
		score += 6
	}
	return score
}

func uniqueStrings(values []string) []string {
	seen := make(map[string]bool, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		key := strings.ToLower(value)
		if seen[key] {
			continue
		}
		seen[key] = true
		result = append(result, value)
	}
	return result
}

func humanizeIdentifier(identifier string) string {
	identifier = strings.TrimSpace(identifier)
	if identifier == "" {
		return ""
	}
	identifier = strings.ReplaceAll(identifier, "_", " ")
	words := strings.Fields(identifier)
	for i, word := range words {
		words[i] = strings.ToUpper(word[:1]) + strings.ToLower(word[1:])
	}
	return strings.Join(words, " ")
}

func (s *glossaryService) glossaryInvestigationPlannerSystemMessage() string {
	return `You identify the strongest investigation areas for example glossary metrics.

Return JSON only.

Rules:
- Return ranked investigation areas, not glossary terms.
- Use only the schema, ontology, and project knowledge provided.
- Prefer areas that can produce one-row aggregate metrics without undocumented parameters.
- Reject vague ideas, arbitrary time windows, or metrics that need business assumptions not present in the input.
- Keep the list to at most 12 areas.

Response format:
{
  "areas": [
    {
      "rank": 1,
      "area": "revenue path",
      "business_rationale": "Completed transactions and payouts are central to the business model.",
      "tables": ["orders", "payments"],
      "focus_columns": ["amount_cents", "status", "created_at"]
    }
  ]
}`
}

func (s *glossaryService) buildGlossaryInvestigationPlanPrompt(autoCtx *glossaryAutoGenerateContext) string {
	var sb strings.Builder
	sb.WriteString("# Example Glossary Investigation Planning\n\n")
	writeDomainSummary(&sb, autoCtx.project.DomainSummary)

	if len(autoCtx.knowledgeFacts) > 0 {
		sb.WriteString("## Project Knowledge\n\n")
		for _, fact := range autoCtx.knowledgeFacts {
			sb.WriteString(fmt.Sprintf("- [%s] %s", fact.FactType, fact.Value))
			if fact.Context != "" {
				sb.WriteString(fmt.Sprintf(" (%s)", fact.Context))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Selected Tables\n\n")
	for _, table := range autoCtx.tables {
		sb.WriteString(fmt.Sprintf("- %s", table.TableName))
		if table.RowCount != nil {
			sb.WriteString(fmt.Sprintf(" (rows=%d)", *table.RowCount))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	writeKeyColumns(&sb, autoCtx.columnMetadataByTable)

	if len(autoCtx.relationships) > 0 {
		sb.WriteString("## Relationship Cues\n\n")
		for _, edge := range autoCtx.relationships {
			sb.WriteString(fmt.Sprintf("- %s.%s -> %s.%s [%s]\n", edge.SourceTable, edge.SourceColumn, edge.TargetTable, edge.TargetColumn, edge.RelationshipType))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("Return only the strongest investigation areas that are likely to yield a rock-solid one-row metric definition.\n")
	return sb.String()
}

func (s *glossaryService) glossarySQLCandidateSystemMessage() string {
	return `You generate one SQL candidate for a verified example glossary metric.

Return JSON only.

Rules:
- Output one single SELECT statement that returns exactly one row.
- Use only the allowed tables, columns, and relationship edges supplied in the prompt.
- Do not invent joins, filters, or time windows.
- Do not use undocumented parameters, cohorts, or geographic bounds.
- If a metric cannot be computed faithfully, return an empty sql field.

Response format:
{
  "sql": "SELECT ...",
  "base_table": "orders",
  "metric_rationale": "Why this metric is reliable from the supplied evidence.",
  "used_tables": ["orders", "payments"]
}`
}

func (s *glossaryService) buildGlossarySQLCandidatePrompt(
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	attempt int,
	lastErr error,
) string {
	var sb strings.Builder
	sb.WriteString("# Investigation Area\n\n")
	sb.WriteString(fmt.Sprintf("- Rank: %d\n", evidence.Area.Rank))
	sb.WriteString(fmt.Sprintf("- Area: %s\n", evidence.Area.Area))
	if evidence.Area.BusinessRationale != "" {
		sb.WriteString(fmt.Sprintf("- Rationale: %s\n", evidence.Area.BusinessRationale))
	}
	sb.WriteString("\n")

	if attempt > 1 && lastErr != nil {
		sb.WriteString("## Previous Attempt Failed\n\n")
		sb.WriteString(lastErr.Error())
		sb.WriteString("\n\n")
	}

	sb.WriteString("## Allowed Tables\n\n")
	for _, table := range evidence.CandidateTables {
		sb.WriteString(fmt.Sprintf("- %s", table.TableName))
		if rowCount, ok := evidence.RowCounts[table.TableName]; ok {
			sb.WriteString(fmt.Sprintf(" (rows=%d)", rowCount))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	if len(evidence.AllowedRelationships) > 0 {
		sb.WriteString("## Allowed Relationship Edges\n\n")
		for _, edge := range evidence.AllowedRelationships {
			sb.WriteString(fmt.Sprintf("- %s.%s -> %s.%s [%s]\n", edge.SourceTable, edge.SourceColumn, edge.TargetTable, edge.TargetColumn, edge.RelationshipType))
		}
		sb.WriteString("\n")
	}

	appendGlossaryCandidateColumns := func(header string, columns []glossaryColumnCandidate) {
		if len(columns) == 0 {
			return
		}
		sb.WriteString("## " + header + "\n\n")
		for _, column := range columns {
			sb.WriteString(fmt.Sprintf("- %s.%s", column.Table, column.Column))
			if column.NonNullCount > 0 {
				sb.WriteString(fmt.Sprintf(" (non_null=%d)", column.NonNullCount))
			}
			if column.Description != "" {
				sb.WriteString(" - " + column.Description)
			}
			if len(column.EnumValues) > 0 {
				sb.WriteString(fmt.Sprintf(" values=%v", column.EnumValues))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	appendGlossaryCandidateColumns("Candidate Measure Columns", evidence.MeasureColumns)
	appendGlossaryCandidateColumns("Candidate Status Columns", evidence.StatusColumns)
	appendGlossaryCandidateColumns("Candidate Time Columns", evidence.TimeColumns)

	if evidence.KnowledgeText != "" {
		sb.WriteString("## Project Knowledge Constraints\n\n")
		sb.WriteString(evidence.KnowledgeText)
		sb.WriteString("\n\n")
	}

	sb.WriteString("Generate the single strongest metric for this area that can be computed faithfully right now.\n")
	return sb.String()
}

func (s *glossaryService) glossaryWriteSystemMessage() string {
	return `You name a verified glossary metric after the SQL is already qualified.

Return JSON only.

Rules:
- Keep the term and definition aligned to what the SQL actually computes.
- Do not introduce new assumptions, time windows, or semantics.
- Prefer a concise, business-appropriate term.

Response format:
{
  "term": "Net Revenue",
  "definition": "Total completed order revenue after applying documented currency normalization.",
  "aliases": ["Revenue"]
}`
}

func (s *glossaryService) buildGlossaryWritePrompt(
	autoCtx *glossaryAutoGenerateContext,
	evidence *glossaryInvestigationEvidence,
	candidate *glossaryQualifiedCandidate,
) string {
	var sb strings.Builder
	sb.WriteString("# Verified Metric\n\n")
	sb.WriteString(fmt.Sprintf("- Investigation area: %s\n", evidence.Area.Area))
	sb.WriteString(fmt.Sprintf("- SQL:\n```sql\n%s\n```\n\n", candidate.SQL))
	sb.WriteString("## Source Tables\n\n")
	for _, table := range candidate.ReferencedTables {
		sb.WriteString("- " + table + "\n")
	}
	sb.WriteString("\n## Output Columns\n\n")
	for _, column := range candidate.OutputColumns {
		sb.WriteString(fmt.Sprintf("- %s (%s)\n", column.Name, column.Type))
	}
	sb.WriteString("\nWrite a term and definition that describe exactly this SQL and nothing more.\n")
	_ = autoCtx
	return sb.String()
}
